apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: {{ .Values.project.namespace }}
spec:
  ports:
  - port: 27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb
  namespace: {{ .Values.project.namespace }}
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      containers:
      - image: quay.io/1927077/open5gs-mongo:latest
        name: open5gs-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
